---
- name: Check 1Password package signing key
  become: true
  become_user: "{{ target_user }}"
  ansible.builtin.command:
    cmd: >-
      gpg --batch --list-keys
      3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  register: packages_onepassword_signing_key
  changed_when: false
  failed_when: false

- name: Import 1Password package signing key
  become: true
  become_user: "{{ target_user }}"
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://downloads.1password.com/linux/keys/1password.asc |
      gpg --batch --import
  args:
    executable: /bin/bash
  when: packages_onepassword_signing_key.rc | default(1) != 0
  changed_when: true
